require('core.mappings')
require('core.setup')
require('manager.lazy')
-- config
require('config.treesiter')
require('config.nvim-cmp')
require('config.lsp')
require('config.yank')
require('config.bufferline')
require("config.format")
require("config.null-ls")
